### ISSUE TITLE
Column parameters in prepared statements

### ISSUE THREAD

**Issue by anttiviljami** [mjdbc/mjdbc#5]
Basic list SQL query use case with support for ordering by column.

```java
@Sql("SELECT * FROM entities LIMIT :limit OFFSET :offset ORDER BY :order_column :ascdesc")
List<Entity> listEntities(
  @Bind("limit") int limit,
  @Bind("offset") int offset,
  @Bind("order_column") String orderColumn,
  @Bind("ascdesc") AscDesc sortOrder
);
```

This obviously wouldn't work because we can't supply column names as parameters with `@Bind` 

How does this work?

**Comment by mfursov** [comment]
Unfortunately this way mJDBC will not be able to create a prepared statement per method.

However you can always use the low-level API to build any query you like. Here is example from one of my projects:
``` java
List<OfferId> offers = db.executeNN(c -> {
            val sql = "SELECT id FROM " + queue.tableName() + " WHERE " + queue.checkField + " <= :maxDate AND local = 0 ORDER BY " + queue.checkField + " LIMIT " + limit;
            return c.prepareStatement(sql, OfferId.MAPPER)
                       .set("maxDate", Timestamp.from(System.currentTimeMillis()))
                       .queryList();
        });
```

I understand that this is less declarative than interface-style API, but this way gives you all power of low-level JDBC + most of the features of mJDBC (transactions, bindings, mappers)
